"""Domain-phrase lexicon: phrase -> {industry, topics} safety net."""

import json

import pytest

from app import config
from app.nodes import _normalise_topics

_VOCAB_PATH = config.REPO_ROOT / "data" / "dataset_vocab.json"
try:
    _VOCAB = json.loads(_VOCAB_PATH.read_text(encoding="utf-8"))
except OSError:                       # artifact absent (fresh clone before profile_dataset)
    _VOCAB = {"core_topics": list(config.core_topics()),
              "noun_heads": ["engine", "infrastructure", "platform", "software",
                             "solution", "system"]}


@pytest.mark.parametrize(
    "phrase, industry, topic",
    [
        ("drug discovery", "Biotech", "drug discovery"),
        ("fraud detection", "Fintech", "fraud detection"),
        ("energy forecasting", "Energy", "energy forecasting"),
        ("smart grid", "Energy", "smart grid"),
        ("autonomous driving", "Automotive", "autonomous driving"),
        ("personalized learning", "Education", "personalized learning"),
        ("5G analytics", "Telecom", "5G analytics"),
    ],
)
def test_phrase_maps_to_industry_and_topic(phrase, industry, topic):
    hits = config.lookup_phrases(f"companies working on {phrase} in Europe")
    match = next(h for h in hits if h.phrase.lower() == phrase.lower())
    assert match.industry == industry
    assert topic in match.topics


def test_every_lexicon_industry_is_in_the_enum():
    for hit in config.lexicon().values():
        assert hit.industry is None or hit.industry in config.INDUSTRIES


def test_cybersecurity_has_no_industry():
    hits = {h.phrase.lower(): h for h in config.lookup_phrases("exclude cybersecurity consultancies")}
    assert hits["cybersecurity"].industry is None
    assert "cybersecurity" in hits["cybersecurity"].topics


def test_lookup_prefers_longer_phrases_first():
    hits = config.lookup_phrases("supply chain visibility platforms")
    # "supply chain visibility" (23 chars) must rank before "supply chain" (12)
    phrases = [h.phrase for h in hits]
    assert phrases.index("supply chain visibility") < phrases.index("supply chain")


def test_no_match_returns_empty():
    assert config.lookup_phrases("a completely unrelated sentence about weather") == []


# --------------------------------------------------------------------------- #
# every real topic in companies.json must be mapped — regression guard so the
# lexicon can't silently drift out of sync with the data.
# `data/dataset_vocab.json` is regenerated by `python -m app.profile_dataset`.
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("topic", _VOCAB["core_topics"])
def test_lexicon_covers_every_core_dataset_topic(topic):
    got, _ = _normalise_topics([topic], [])
    assert topic in got, f"{topic!r} from companies.json is not mapped by app/lexicon.yaml"


@pytest.mark.parametrize("noun", _VOCAB["noun_heads"])
def test_topic_resolves_with_any_template_noun_head(noun):
    """"fraud detection engine", "fraud detection infrastructure", … must all
    still resolve to the bare topic (users paste the description wording)."""
    unresolved = []
    for topic in _VOCAB["core_topics"]:
        got, _ = _normalise_topics([f"{topic} {noun}"], [])
        if topic not in got:
            unresolved.append(topic)
    assert not unresolved, f"'<topic> {noun}' failed for: {unresolved}"


@pytest.mark.parametrize(
    "british, american",
    [
        ("supply chain optimisation", "supply chain optimization"),
        ("Personalised learning", "personalized learning"),
        ("analyse the data", "analyze the data"),
        ("customised platform", "customized platform"),
    ],
)
def test_normalise_spelling(british, american):
    assert config.normalise_spelling(british.lower()) == american


@pytest.mark.parametrize(
    "phrase, industry",
    [
        ("Personalised learning", "Education"),          # british spelling
        ("supply chain optimisation", "Logistics"),      # british + generic tail
        ("cybercrime prevention", "Fintech"),            # synonym -> fraud detection
        ("precision medicine", "Biotech"),               # synonym
    ],
)
def test_lexicon_handles_spelling_and_synonyms(phrase, industry):
    hits = config.lookup_phrases(phrase)
    assert any(h.industry == industry for h in hits), (phrase, [h.phrase for h in hits])
